In [1]:
import pandas as pd

results_df = pd.read_csv("./data/eval_prs_cleaned_w_metrics_3.csv")
results_df

,question,answer,issue_url,edit_functions,problem_statement,comments,pr_problem_statement,pr_comments,precision_3,recall_3,...,mrr,bleu,meteor,bertscore,faithfulness,answer_relevancy,semantic_similarity,generated_answer,retrieved_functions,retrieved_docs
0,How do you handle the concept of inheritance i...,"In a multilevel model, you can handle the conc...",https://github.com/scikit-learn/scikit-learn/p...,"['PrecisionRecallDisplay.__init__', 'Precision...",NaN,NaN,ENH: Standardize parameter naming in Precision...,NaN,0.0,0.000000,...,0.0,0.007587,0.167364,0.074459,NaN,NaN,0.389668,"From the provided context, it seems that the c...","['LinearClassifierMixin._predict_proba_lr', 'L...","[Document(metadata={'type': 'function_code', '..."
1,What is the purpose of setting `requires_fit=F...,"This change sets the `""requires_fit""` tag to `...",https://github.com/scikit-learn/scikit-learn/p...,"['FeatureHasher._get_tags', 'TfidfVectorizer._...",NaN,NaN,Set requires_fit=False for FeatureHasher and H...,NaN,0.0,0.000000,...,0.0,0.131212,0.551832,0.476287,NaN,NaN,0.855221,The purpose of setting `requires_fit=False` fo...,"['HashingVectorizer.fit', 'test_feature_hasher...","[Document(metadata={'type': 'pr_title', 'node_..."
2,Why did the author?,This PR exposes the `requires_fit=False` tag f...,https://github.com/scikit-learn/scikit-learn/p...,"['FeatureHasher._more_tags', 'HashingVectorize...",NaN,NaN,MAINT: Add requires_fit=False tag for FeatureH...,NaN,0.0,0.000000,...,0.0,0.008629,0.144033,-0.017891,NaN,NaN,0.239696,"From the provided context, it appears that the...","['MetadataRouter._get_param_names', 'MetadataR...","[Document(metadata={'type': 'function_code', '..."
3,Why were the `requires_fit` tags set to `False...,The `requires_fit` tags were set to `False` be...,https://github.com/scikit-learn/scikit-learn/p...,"['FeatureHasher.__sklearn_tags__', 'test_featu...",NaN,NaN,Fix requires_fit tag for stateless FeatureHash...,NaN,1.0,0.333333,...,1.0,0.183033,0.550296,0.331607,NaN,NaN,0.695830,The `requires_fit` tags were set to `False` fo...,"['test_feature_hasher_requires_fit_tag', 'test...","[Document(metadata={'type': 'pr_title', 'node_..."
4,What is the purpose of modifying the error mes...,This improvement fixes a misleading error mess...,https://github.com/scikit-learn/scikit-learn/p...,"['_check_sample_weight_common', '_check_sample...",NaN,NaN,modifying the error message for _check_sample_...,NaN,0.0,0.000000,...,0.0,0.020447,0.277731,0.105441,NaN,NaN,0.505156,The purpose of modifying the error message for...,[],"[Document(metadata={'type': 'issue_body', 'nod..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264,What is the issue this pull request is suppose...,The.,https://github.com/scikit-learn/scikit-learn/p...,"['config_context', 'set_config', 'sag_solver']",NaN,NaN,Adds convergence warning suppression via globa...,NaN,0.0,0.000000,...,0.0,0.005568,0.116279,-0.379248,NaN,NaN,0.060923,This Pull Request is supposed to fix the issue...,[],"[Document(metadata={'type': 'issue_body', 'nod..."
265,What is the purpose of the `get_response_value...,It is used to select the positive class for bi...,https://github.com/scikit-learn/scikit-learn/p...,['test_partial_dependence_binary_model_grid_re...,NaN,NaN,FIX: Fix for binary classifier prediction shap...,NaN,0.0,0.000000,...,0.0,0.006127,0.174129,0.077174,NaN,NaN,0.451048,The `get_response_values` function computes th...,['PartialDependenceDisplay._plot_average_depen...,"[Document(metadata={'type': 'function_code', '..."
266,What is the purpose of the `sklearn/linear_mod...,This pull request fixes a typo in the docstrin...,https://github.com/scikit-learn/scikit-learn/p...,['_ridge_regression'],NaN,NaN,MAINT: remove unused local var in `sklearn.lin...,NaN,0.0,0.000000,...,0.0,0.020186,0.404587,0.183335,NaN,NaN,0.322423,"The pull request titled ""MAINT: remove unused ...","['PredictionErrorDisplay.from_estimator', '_ch...","[Document(metadata={'type': 'function_code', '..."
267,What was the purpose of the recent changes in ...,The purpose was to document the version added ...,https://github.com/scikit-learn/scikit-learn/p...,['get_tags'],NaN,NaN,DOC: Document version added\nIt's useful to kn...,NaN,0.0,0.000000,...,0.0,0.008109,0.149007,0.094410,NaN,NaN,0.493201,The changes in `sklearn/utils/_tags.py:get_tag...,"['CheckingClassifier.__sklearn_tags__', 'Class...","[Document(metadata={'type': 'function_code', '..."
268,What is the purpose of the changes made to the...,The changes aim to reflect the recent updates ...,https://github.com/scikit-learn/scikit-learn/p...,['get_contributors'],NaN,NaN,DOC: some maintainers become emeritus\nThis re...,NaN,0.0,0.000000,...,0.0,0.032086,0.374089,0.208516,NaN,NaN,0.628798,The changes made to the `get_contributors` fun...,"['_IgnoreWarnings.__repr__', '_MetadataRequest...","[Document(metadata={'type': 'function_code', '..."

In [2]:
general_qa_df = results_df[results_df["category"] == "general"]
general_qa_df

,function_code,category,question,answer,edit_functions,precision_3,recall_3,f1_3,iou_3,precision_5,...,bleu,meteor,bertscore,faithfulness,answer_relevancy,semantic_similarity,generated_answer,retrieved_functions,retrieved_docs,pred_query_class
0,"def predict_log_proba(self, X):\n """"""Estima...",general,What input data does the predict_log_proba fun...,"It accepts an array-like of shape (n_samples, ...",[],0.0,0.0,0.0,0.0,0.0,...,0.015708,0.301005,0.045272,NaN,NaN,0.256327,The `predict_log_proba` function accepts a 2D ...,"['BaggingClassifier.predict_log_proba', 'Decis...",[Document(metadata={'type': 'function_docstrin...,general_qa
1,def test_correct_shapes():\n assert orthogo...,general,What does the `test_correct_shapes` function v...,The `test_correct_shapes` function verifies th...,[],0.0,0.0,0.0,0.0,0.0,...,0.453807,0.740521,0.725111,NaN,NaN,0.900626,The `test_correct_shapes` function verifies th...,"['orthogonal_mp', 'orthogonal_mp_gram', 'paire...",[Document(metadata={'type': 'function_docstrin...,general_qa
2,"def get_metadata_routing(self):\n """"""Get me...",general,What does the `get_metadata_routing` function ...,A `MetadataRouter` encapsulating routing infor...,[],0.0,0.0,0.0,0.0,0.0,...,0.006485,0.183824,0.040369,NaN,NaN,0.604316,The `get_metadata_routing` function returns ei...,"['IterativeImputer.fit_transform', 'MetadataRo...",[Document(metadata={'type': 'function_docstrin...,general_qa
3,"@pytest.mark.parametrize('kernel', kernels)\nd...",general,What is the purpose of the `test_kernel_clone`...,This function tests whether a kernel clone is ...,[],0.0,0.0,0.0,0.0,0.0,...,0.023979,0.250335,0.181681,NaN,NaN,0.763507,The purpose of the `test_kernel_clone` functio...,['_BinaryGaussianProcessClassifierLaplace.log_...,"[Document(metadata={'type': 'function_name', '...",general_qa
13,"@pytest.mark.parametrize('check_input', [True,...",general,What is the purpose of the test_enet_copy_X_Tr...,The purpose of the test_enet_copy_X_True funct...,[],0.0,0.0,0.0,0.0,0.0,...,0.040614,0.281690,0.285757,NaN,NaN,0.765524,The purpose of the `test_enet_copy_X_True` fun...,"['TfidfTransformer.transform', '_PLS.predict',...","[Document(metadata={'type': 'function_name', '...",general_qa
14,@ignore_warnings(category=DeprecationWarning)\...,general,What is the purpose of the test_pairwise_boole...,This function tests the pairwise_distances fun...,[],0.0,0.0,0.0,0.0,0.0,...,0.007726,0.190972,0.085435,NaN,NaN,0.733245,The `test_pairwise_boolean_distance` function ...,"['_hdbscan_brute', 'pairwise_distances', 'pair...","[Document(metadata={'type': 'function_name', '...",general_qa
15,"def _available_if_estimator_has(attr):\n """"...",general,What is the purpose of the _available_if_estim...,This function is used to check if the sub-esti...,[],0.0,0.0,0.0,0.0,0.0,...,0.101811,0.315844,0.184787,NaN,NaN,0.710264,The `available_if_estimator_has` function is u...,"['_available_if_base_estimator_has', '_availab...",[Document(metadata={'type': 'function_docstrin...,general_qa
16,"@pytest.mark.parametrize('curve_func', CURVE_F...",general,What is the purpose of the test_binary_clf_cur...,This function tests the binary classification ...,[],0.0,0.0,0.0,0.0,0.0,...,0.043196,0.325401,0.188094,NaN,NaN,0.672863,The purpose of the `test_binary_clf_curve_zero...,"['_binary_clf_curve', 'test_binary_classifier_...","[Document(metadata={'type': 'function_name', '...",general_qa
29,@_fit_context(prefer_skip_nested_validation=Tr...,general,What is the role of the super().fit_transform(...,This method is used to fit and transform the r...,[],0.0,0.0,0.0,0.0,0.0,...,0.075772,0.574384,0.180589,NaN,NaN,0.735949,The `super().fit_transform(raw_documents)` met...,"['FeatureUnion.fit', 'FeatureUnion.fit_transfo...",[Document(metadata={'type': 'function_docstrin...,general_qa
30,"@pytest.mark.parametrize('loss', ('squared_err...",general,What is the purpose of this function?,This function tests the performance of a regre...,[],0.0,0.0,0.0,0.0,0.0,...,0.005520,0.240309,0.122863,NaN,NaN,0.553383,The purpose of this function is to convert the...,"['BaseMixture._initialize_parameters', 'Missin...",[Document(metadata={'type': 'function_docstrin...,general_qa
31,def test_no_collision_on_byte_range():\n pr...,general,"What is the purpose of the ""test_no_collision_...",This function tests that there are no collisio...,[],0.0,0.0,0.0,0.0,0.0,...,0.050444,0.336279,0.092309,NaN,NaN,0.528333,"The ""test_no_collision_on_byte_range"" function...","['LatentDirichletAllocation._approx_bound', '_...","[Document(metadata={'type': 'function_name', '...",general_qa
44,def test_grid_search_failing_classifier_raise(...,general,What is the purpose of this function?,The function is designed to test the grid sear...,[],0.0,0.0,0.0,0.0,0.0,...,0.011505,0.188158,0.091239,NaN,NaN,0.479626,This function converts the output of `decision...,"['BaseMixture._initialize_parameters', 'Missin...",[Document(metadata={'type': 'function_docstrin...,general_qa
45,"def check_warning():\n clf = RNC(radius=1, ...",general,"What is the purpose of the function ""check_war...",It fits a classifier and predicts probabilitie...,[],0.0,0.0,0.0,0.0,0.0,...,0.005627,0.135135,-0.051433,NaN,NaN,0.196140,"The purpose of the function ""check_warning"" is...","['MetadataRequest._check_warnings', '_check_se...","[Document(metadata={'type': 'function_name', '...",general_qa
46,@ignore_warnings(category=FutureWarning)\ndef ...,general,What is the purpose of the check_transformers_...,This function checks if a transformer is unfit...,[],0.0,0.0,0.0,0.0,0.0,...,0.011236,0.255474,0.164630,NaN,NaN,0.739567,The purpose of the `check_transformers_unfitte...,"['ColumnTransformer._validate_transformers', '...","[Document(metadata={'type': 'function_name', '...",general_qa
47,def test_multi_output_classification_partial_f...,general,How does the test_multi_output_classification_...,The test_multi_output_classification_partial_f...,[],0.0,0.0,0.0,0.0,0.0,...,0.006233,0.203252,0.074585,NaN,NaN,0.892572,The `test_multi_output_classification_partial_...,"['accuracy_score', 'test_multi_output_classifi...","[Document(metadata={'type': 'function_name', '...",general_qa
58,def __sklearn_tags__(self):\n tags = super(...,general,What is the purpose of the `__sklearn_tags__` ...,The purpose of the `__sklearn_tags__` function...,[],0.0,0.0,0.0,0.0,0.0,...,0.112686,0.359050,0.327494,NaN,NaN,0.818914,The purpose of the `__sklearn_tags__` function...,"['check_estimator_tags_renamed', 'default_tags...",[Document(metadata={'type': 'function_docstrin...,general_qa
59,"@pytest.mark.parametrize('csr_container', CSR_...",general,What does the `test_mean_variance_illegal_axis...,This function tests the handling of illegal ax...,[],0.0,0.0,0.0,0.0,0.0,...,0.134555,0.592695,0.378828,NaN,NaN,0.872380,The `test_mean_variance_illegal_axis` function...,"['incr_mean_variance_axis', 'mean_variance_axi...","[Document(metadata={'type': 'function_name', '...",general_qa
60,def test_set_random_states():\n _set_random...,general,What is the primary function of the `_set_rand...,. (Please fill in your answer).,[],0.0,0.0,0.0,0.0,0.0,...,0.006239,0.135135,-0.208422,NaN,NaN,0.081073,The `_set_random_states` helper function in th...,"['AdaBoostClassifier._boost', '_set_random_sta...",[Document(metadata={'type': 'function_docstrin...,general_qa
61,"@pytest.mark.parametrize('interval_type', [Int...",general,What is the purpose of the test_interval_range...,The purpose of the test_interval_range functio...,[],0.0,0.0,0.0,0.0,0.0,...,0.033137,0.137041,0.022334,NaN,NaN,0.841189,The purpose of the `test_interval_range` funct...,"['Interval.includes', '_inclusive_low_high', '...","[Document(metadata={'type': 'function_name', '...",general_qa
74,"@pytest.mark.parametrize('name', SPARSE_TREES)...",general,What is the purpose of the test_min_weight_fra...,It tests the min_weight_fraction_leaf function...,[],0.0,0.0,0.0,0.0,0.0,...,0.010896,0.194805,0.191466,NaN,NaN,0.853638,The `test_min_weight_fraction_leaf_on_sparse_i...,"['compute_optics_graph', 'laplacian', 'test_co...","[Document(metadata={'type': 'function_name', '...",general_qa
75,"def test_get_chunk_n_rows_warns():\n """"""Che...",general,What is the purpose of the test_get_chunk_n_ro...,This function checks that a warning is raised ...,[],0.0,0.0,0.0,0.0,0.0,...,0.076670,0.314811,0.108477,NaN,NaN,0.770820,The `test_get_chunk_n_rows_warns` function app...,"['_check_chunk_size', 'argsort', 'get_chunk_n_...","[Document(metadata={'type': 'function_name', '...",general_qa
76,"def test_lasso_cv():\n X, y, X_test, y_test...",general,What is the purpose of the test_lasso_cv funct...,The test_lasso_cv function is used to evaluate...,[],0.0,0.0,0.0,0.0,0.0,...,0.017275,0.320224,0.250964,NaN,NaN,0.790800,The `test_lasso_cv` function appears to be a t...,"['_assert_graphical_lasso_cv_scores', 'test_gr...","[Document(metadata={'type': 'function_name', '...",general_qa
77,"@pytest.mark.parametrize('tree_type, criterion...",general,What is the purpose of the test_sparse_criteri...,The purpose of the test_sparse_criteria functi...,[],0.0,0.0,0.0,0.0,0.0,...,0.052884,0.346216,0.199677,NaN,NaN,0.691739,The purpose of the `test_sparse_criteria` func...,"['test_exact_no_precomputed_sparse', 'test_sma...","[Document(metadata={'type': 'function_name', '...",general_qa
89,"def _fit_transform(self, X):\n if self.n_ne...",general,What is the effect of providing both n_neighbo...,"It will raise a ValueError, indicating that bo...",[],0.0,0.0,0.0,0.0,0.0,...,0.012229,0.242937,0.009967,NaN,NaN,0.228925,Providing both `n_neighbors` and `radius` para...,"['LocallyLinearEmbedding._fit_transform', 'Rad...",[Document(metadata={'type': 'function_docstrin...,general_qa
90,"@pytest.mark.parametrize('name, dataset_func',...",general,What is the function test_common_check_as_fram...,It tests the functionality of a dataset conver...,[],0.0,0.0,0.0,0.0,0.0,...,0.034343,0.422247,0.207343,NaN,NaN,0.721707,The function `test_common_check_as_frame` is u...,"['check_as_frame', 'test_20news_as_frame', 'te...","[Document(metadata={'type': 'function_name', '...",general_qa
91,def test_center_kernel():\n rng = np.random...,general,What is the purpose of the test_center_kernel ...,This function tests the correctness of a kerne...,[],0.0,0.0,0.0,0.0,0.0,...,0.023341,0.314811,0.046812,NaN,NaN,0.682262,The purpose of the `test_center_kernel` functi...,"['test_center_kernel', 'test_implicit_center_m...","[Document(metadata={'type': 'function_name', '...",general_qa
103,"def build_preprocessor(self):\n """"""Return a...",general,What is the function build_preprocessor used for?,It returns a function to preprocess the text b...,[],0.0,0.0,0.0,0.0,0.0,...,0.005101,0.067288,-0.171827,NaN,NaN,0.227600,The `build_preprocessor` function is used for ...,"['_RidgeGCV._compute_gram', '_VectorizerMixin....","[Document(metadata={'type': 'function_name', '...",general_qa
104,@validate_params({'n_samples': [Interval(Integ...,general,<your question?>?,<your answer.>.,[],0.0,0.0,0.0,0.0,0.0,...,0.004349,0.073529,-0.318526,NaN,NaN,0.118027,"The question isn't specified. However, based o...","['Interval.__post_init__', '_maybe_mark', 'at....",[Document(metadata={'type': 'function_docstrin...,general_qa
105,def test_ransac_no_valid_model():\n\n def i...,general,What is the default value of the max_trials pa...,The.,[],0.0,0.0,0.0,0.0,0.0,...,0.005368,0.112360,-0.376058,NaN,NaN,0.072479,The `RANSACRegressor` does not have a default ...,"['BaseBagging._fit', '_dynamic_max_trials', '_...",[Document(metadata={'type': 'function_docstrin...,general_qa
117,def test_early_stopping_with_sample_weights(mo...,general,What is the purpose of the `test_early_stoppin...,The purpose of the `test_early_stopping_with_s...,[],0.0,0.0,0.0,0.0,0.0,...,0.064315,0.347735,0.256664,NaN,NaN,0.785973,The `test_early_stopping_with_sample_weights` ...,['test_X_val_raises_with_early_stopping_false'...,"[Document(metadata={'type': 'function_name', '...",general_qa
118,def func(X):\n assert_array_equal(X.columns...,general,What does the func function do when it is call...,This function compares the columns and values ...,[],0.0,0.0,0.0,0.0,0.0,...,0.022113,0.226700,0.155330,NaN,NaN,0.466118,The `func` function computes pairwise distance...,"['_check_set_output_transform_pandas_context',...",[Document(metadata={'type': 'function_docstrin...,general_qa
119,"@pytest.mark.parametrize('solver', SOLVERS)\n@...",general,"What is the purpose of this function, which te...",This function tests that unpenalized Ridge reg...,[],0.0,0.0,0.0,0.0,0.0,...,0.020544,0.238182,0.017506,NaN,NaN,0.673073,The provided functions are testing different i...,"['_ridge_regression', 'test_ridge_positive_reg...","[Document(metadata={'type': 'function_code', '...",performance_issue
120,"@pytest.mark.parametrize('Stacker, Estimator, ...",general,What is the purpose of the `test_stacking_pref...,This function tests the behavior of stacking w...,[],0.0,0.0,0.0,0.0,0.0,...,0.022742,0.354009,0.148578,NaN,NaN,0.743822,The `test_stacking_prefit` function in the giv...,"['test_config_threadsafe', 'test_metadata_rout...","[Document(metadata={'type': 'function_name', '...",general_qa
131,"@pytest.mark.filterwarnings(""ignore:.*'multi_c...",general,** What is the purpose of the test_max_iter fu...,** This function tests the maximum number of i...,[],0.0,0.0,0.0,0.0,0.0,...,0.010972,0.154930,0.125004,NaN,NaN,0.559030,The purpose of the `test_max_iter` function is...,"['BaseSGDClassifier.partial_fit', '_lars_path_...",[Document(metadata={'type': 'function_docstrin...,general_qa
132,"@pytest.mark.parametrize('dtype_in', [np.float...",general,What is the purpose of the test_select_kbest_z...,This function tests the SelectKBest function w...,[],0.0,0.0,0.0,0.0,0.0,...,0.007549,0.195730,0.021314,NaN,NaN,0.586204,The purpose of the `test_select_kbest_zero` fu...,"['jax_autojit', 'test_exactly_zero_info_score'...","[Document(metadata={'type': 'function_name', '...",general_qa
133,@_fit_context(prefer_skip_nested_validation=Fa...,general,What is the purpose of the `fit_transform` fun...,This function fits the input data `X` into an ...,[],0.0,0.0,0.0,0.0,0.0,...,0.036526,0.261097,0.158532,NaN,NaN,0.524451,The `fit_transform` function in this class is ...,"['MiniBatchNMF._fit_transform', 'MiniBatchNMF....",[Document(metadata={'type': 'function_docstrin...,general_qa
134,"@pytest.mark.parametrize('strategy, expected',...",general,How does the test_simple_imputation_string_lis...,This function uses the SimpleImputer class to ...,[],0.0,0.0,0.0,0.0,0.0,...,0.008287,0.215385,0.055487,NaN,NaN,0.621308,The `test_simple_imputation_string_list` funct...,"['_check_statistics', 'test_imputation_constan...","[Document(metadata={'type': 'function_name', '...",general_qa
146,@pytest.mark.parametrize('min_dependencies_tag...,general,What is the purpose of the test_min_dependenci...,This function checks that the versions in the ...,[],0.0,0.0,0.0,0.0,0.0,...,0.082696,0.338934,0.190857,NaN,NaN,0.868319,The `test_min_dependencies_pyproject_toml` fun...,"['check_pyproject_section', 'test_min_dependen...","[Document(metadata={'type': 'function_name', '...",general_qa
147,@ignore_warnings(category=DeprecationWarning)\...,general,What is the purpose of the test_kneighbors_bru...,This function tests the brute-force nearest ne...,[],0.0,0.0,0.0,0.0,0.0,...,0.019935,0.176391,0.044092,NaN,NaN,0.670881,The `test_kneighbors_brute_backend` function i...,"['PartialDependenceDisplay.from_estimator', 'c...","[Document(metadata={'type': 'function_name', '...",general_qa
148,"@pytest.mark.parametrize('coo_container', COO_...",general,What is the purpose of the test_inverse_transf...,The purpose of the test_inverse_transform func...,[],0.0,0.0,0.0,0.0,0.0,...,0.063025,0.329785,0.365493,NaN,NaN,0.810459,The `test_inverse_transform` function appears ...,"['BaseSearchCV.inverse_transform', 'Transforme...",[Document(metadata={'type': 'function_docstrin...,general_qa
149,"@pytest.mark.parametrize('csr_container', CSR_...",general,What are the error messages that the `test_lab...,The function is expecting to raise a `ValueErr...,[],0.0,0.0,0.0,0.0,0.0,...,0.041967,0.296759,0.013846,NaN,NaN,0.373106,The `test_label_binarizer_sparse_errors` funct...,"['_num_samples', 'label_binarize']","[Document(metadata={'type': 'function_code', '...",bug_report
160,"def std(x: Array, /, *, axis: Optional[Union[i...",general,What is the default value of the correction pa...,The default value of the correction parameter.,[],0.0,0.0,0.0,0.0,0.0,...,0.447102,0.816679,0.619507,NaN,NaN,0.666607,The default value of the correction parameter ...,"['DummyRegressor.predict', 'GaussianProcessReg...",[Document(metadata={'type': 'function_docstrin...,general_qa
161,def test_pipeline_with_nearest_neighbors_trans...,general,What is the purpose of the `test_pipeline_with...,This function tests the functionality of pipel...,[],0.0,0.0,0.0,0.0,0.0,...,0.032531,0.225564,0.173571,NaN,NaN,0.718684,The `test_pipeline_with_NearestNeighborsTransf...,"['KNeighborsTransformer.fit', 'Pipeline.invers...","[Document(metadata={'type': 'function_name', '...",general_qa
162,def assert_compatible_radius_results(neighbors...,general,What does the `assert_compatible_radius_result...,This function checks that the results of radiu...,[],0.0,0.0,0.0,0.0,0.0,...,0.029923,0.272650,0.165623,NaN,NaN,0.762549,The `assert_compatible_radius_results` functio...,"['RadiusNeighborsMixin.radius_neighbors', '_ra...","[Document(metadata={'type': 'function_code', '...",general_qa
163,def __sklearn_tags__(self):\n tags = super(...,general,What does the `__sklearn_tags__` function do?,This function overrides the default behavior o...,[],0.0,0.0,0.0,0.0,0.0,...,0.012568,0.160256,0.097867,NaN,NaN,0.434659,The `__sklearn_tags__` function in the given c...,"['check_estimator_tags_renamed', 'default_tags...",[Document(metadata={'type': 'function_docstrin...,general_qa
175,"def _build_graph(self):\n """"""Graph matrix f...",general,** What is the purpose of the _build_graph fun...,** This function computes the graph laplacian ...,[],0.0,0.0,0.0,0.0,0.0,...,0.012903,0.288763,-0.005892,NaN,NaN,0.440886,The `_build_graph` function is a private utili...,"['LabelPropagation._build_graph', 'LabelSpread...","[Document(metadata={'type': 'function_name', '...",general_qa
176,"@validate_params({'data_home': [str, os.PathLi...",general,What is the purpose of the `clear_data_home` f...,It deletes all the content of the data home ca...,[],0.0,0.0,0.0,0.0,0.0,...,0.022561,0.222754,-0.003453,NaN,NaN,0.586856,The `clear_data_home` function is designed to ...,"['_retry_with_clean_cache', 'clear_data_home',...",[Document(metadata={'type': 'function_docstrin...,general_qa

In [ ]:
general_qa_df

In [17]:
results_df.loc[results_df["pred_query_class"] == "bug_report", ['question']].iloc[0].values[0]

'** What is the likely cause of the non-deterministic failure of the `test_unsorted_indices` function in `SVC` when trained on dense vs sparse data?'

In [16]:
results_df.loc[results_df["pred_query_class"] == "bug_report", ['edit_functions']].iloc[0].values[0]

"['_BaseScorer._routing_repr', '_PassthroughScorer.__repr__', '_PassthroughScorer._routing_repr', 'Base.split', 'Class_1.split', 'Consumer.fit', 'OddEstimator.fit', 'TestDefaults.fit', 'TestDefaults.predict', 'TestDefaults.score']"

In [12]:
from ast import literal_eval
results_df.loc[results_df["pred_query_class"] == "bug_report", ["retrieved_docs"]].iloc[0].values[0]

'[Document(metadata={\'type\': \'issue_body\', \'node_id\': 31722, \'doc_id\': \'b6eaef59-a28f-4b25-97df-e0812c2e2001\', \'_id\': \'83b6e50c-5189-406d-bce4-df373f913bc8\', \'_collection_name\': \'rag_collection_all-MiniLM-L6-v2_cosine\'}, page_content=\'[<code>test_unsorted_indices</code>](https://github.com/scikit-learn/scikit-learn/blob/cfd5f7833dfb3794e711e79e4a3373e599d5a1f0/sklearn/svm/tests/tes\'), Document(metadata={\'type\': \'issue_body\', \'node_id\': 31722, \'doc_id\': \'0c32126a-083c-41ae-9d00-2d3a4b029bd9\', \'_id\': \'3e55a525-7a99-4ec9-838d-ffeb127a9fe8\', \'_collection_name\': \'rag_collection_all-MiniLM-L6-v2_cosine\'}, page_content=\'function occasionally fails on CI when comparing the coefficients of `SVC(kernel="linear", probability=True, random_state=0)` trained on dense vs\'), Document(metadata={\'type\': \'issue_body\', \'node_id\': 1905, \'doc_id\': \'989d2f30-8623-4077-a88c-a2d446466570\', \'_id\': \'de4043be-8932-42ff-a041-ed4bdb1a2901\', \'_collection_name\': \'rag_collection_all-MiniLM-L6-v2_cosine\'}, page_content=\'I recently installed scikit tool and when testing it got error. Test of the sparse Linear SVC with iris data set failed with the following assertion\'), Document(metadata={\'type\': \'issue_body\', \'node_id\': 2737, \'doc_id\': \'5ebc212a-df5a-4de7-a417-7c2d910fa0e4\', \'_id\': \'f5290052-6e59-4e68-b1f2-b11718459dc1\', \'_collection_name\': \'rag_collection_all-MiniLM-L6-v2_cosine\'}, page_content=\'---\\n\\n```\\nFAIL: sklearn.svm.tests.test_sparse.test_timeout\'), Document(metadata={\'type\': \'issue_body\', \'node_id\': 19654, \'doc_id\': \'f01d858a-1944-4bc3-bd5e-f44f1fcbb1ce\', \'_id\': \'b80bad74-33fb-4be4-9adf-499348202a59\', \'_collection_name\': \'rag_collection_all-MiniLM-L6-v2_cosine\'}, page_content=\'### Describe the bug\\r\\n\\r\\n*SVC().fit(X, y, w)* sometimes fails with sparse *X* and *w* containing some zeros, raising:\\r\\n```python\'), Document(metadata={\'type\': \'issue_body\', \'node_id\': 19447, \'doc_id\': \'40b44928-b426-422d-b429-47e1828dcf97\', \'_id\': \'ff07f9e0-a86e-455e-be0e-59395019b983\', \'_collection_name\': \'rag_collection_all-MiniLM-L6-v2_cosine\'}, page_content=\'I suspect some form of memoization or extreme low sensitivity happening in the SVC `predict_proba(...)` implementation whereby once a SVC model is\'), Document(metadata={\'type\': \'issue_body\', \'node_id\': 918, \'doc_id\': \'4f5e35a8-dffc-43be-81c1-de4caec57467\', \'_id\': \'79a3bc06-d64f-4b18-8b81-d616dc3489d8\', \'_collection_name\': \'rag_collection_all-MiniLM-L6-v2_cosine\'}, page_content=\'When the feature matrix `X` passed to an `SVC` is sparse and the kernel is a callable, it never gets called. Instead, the SVM seems to just go ahead\'), Document(metadata={\'type\': \'issue_body\', \'node_id\': 31722, \'doc_id\': \'91c58af5-ae70-4672-8d82-63b3738876fa\', \'_id\': \'2d828373-6f07-40bd-b890-aa4d628d1e65\', \'_collection_name\': \'rag_collection_all-MiniLM-L6-v2_cosine\'}, page_content=\'# make sure dense and sparse SVM give the same result\\n    assert_allclose(coef_dense, coef_sorted.toarray(), **tols)\\n```\'), Document(metadata={\'type\': \'issue_body\', \'node_id\': 21410, \'doc_id\': \'b74f85f3-24a9-4b1f-a933-71c506526878\', \'_id\': \'aa08757a-6c45-42c8-9e9f-83814e5ee070\', \'_collection_name\': \'rag_collection_all-MiniLM-L6-v2_cosine\'}, page_content="I\'ve noticed a rather strange behavior when using **Scikit-Learn\'s SVC** implementation. Using the **built-in rbf kernel** with SVC is **slower** by"), Document(metadata={\'type\': \'issue_body\', \'node_id\': 5150, \'doc_id\': \'60c3f1fc-af5d-4de8-810a-c14c01d8ff0e\', \'_id\': \'4f29ce44-be18-4e65-987b-283d67c8be62\', \'_collection_name\': \'rag_collection_all-MiniLM-L6-v2_cosine\'}, page_content=\'This bug appears in current master, and for any dense svm class.\')]'

In [21]:
results_df["pred_query_class"].value_counts()

pred_query_class
general_qa           98
feature_request      35
performance_issue    29
bug_report           20
Name: count, dtype: int64

In [22]:
eval_cols = ['precision_3', 'recall_3', 'f1_3', 'iou_3', 'precision_5', 'recall_5',
       'f1_5', 'iou_5', 'precision_10', 'recall_10', 'f1_10', 'iou_10', 'mrr',
       'bleu', 'meteor', 'bertscore',
       'semantic_similarity']
results_df.groupby("pred_query_class")[eval_cols].mean(numeric_only=True)

,precision_3,recall_3,f1_3,iou_3,precision_5,recall_5,f1_5,iou_5,precision_10,recall_10,f1_10,iou_10,mrr,bleu,meteor,bertscore,semantic_similarity
pred_query_class,,,,,,,,,,,,,,,,,
bug_report,0.0,0.0,0.0,0.1,0.0,0.0,0.0,0.1,0.0,0.0,0.0,0.1,0.0,0.048544,0.267052,0.108379,0.569508
feature_request,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.063135,0.278743,0.152587,0.581315
general_qa,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.071434,0.296367,0.133273,0.605161
performance_issue,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.066011,0.292780,0.148005,0.580316

In [4]:
results_df.loc[results_df["mrr"]>0].describe()

,problem_statement,comments,pr_comments,precision_3,recall_3,f1_3,iou_3,precision_5,recall_5,f1_5,...,recall_10,f1_10,iou_10,mrr,bleu,meteor,bertscore,faithfulness,answer_relevancy,semantic_similarity
count,0.0,0.0,0.0,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000,...,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000,0.0,0.0,90.000000
mean,NaN,NaN,NaN,0.203704,0.234753,0.191928,0.131555,0.184074,0.378377,0.213476,...,0.540335,0.214152,0.132719,0.409653,0.053379,0.306954,0.148921,NaN,NaN,0.605937
std,NaN,NaN,NaN,0.266500,0.339283,0.248798,0.190301,0.208734,0.398409,0.208711,...,0.382092,0.166946,0.142845,0.358873,0.049411,0.110367,0.119989,NaN,NaN,0.179607
min,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.034483,0.005012,0.122951,-0.096409,NaN,NaN,0.209463
25%,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.200000,0.153846,0.083333,0.125000,0.017425,0.228325,0.073698,NaN,NaN,0.511052
50%,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.200000,0.200000,0.250000,...,0.500000,0.181818,0.100000,0.250000,0.037902,0.290618,0.147152,NaN,NaN,0.611950
75%,NaN,NaN,NaN,0.333333,0.500000,0.400000,0.250000,0.200000,0.666667,0.333333,...,1.000000,0.250000,0.142857,0.500000,0.066922,0.380456,0.220554,NaN,NaN,0.746014
max,NaN,NaN,NaN,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,0.210885,0.594667,0.377641,NaN,NaN,0.929033

In [8]:
import csv 

rows = []
with open('./data/eval_prs_filtered.csv',newline='') as csvfile:
    spamreader = csv.reader(csvfile,delimiter=';')
    for row in spamreader:
        rows.append(row)

df = pd.DataFrame(rows[1:], columns=rows[0])
print(df.head())

                                            question  \
0  How do you handle the concept of inheritance i...
1  What is the purpose of setting `requires_fit=F...
2  What is the purpose of the `transform` functio...
3  Why was the CI check modified in the Azure ins...
4  What is the purpose of the `transform` method ...

                                              answer  \
0  In a multilevel model, you can handle the conc...
1  This change sets the `"requires_fit"` tag to `...
2  It applies the learned linear transformation t...
3  The CI check was modified to remove quotes fro...
4  The `transform` method is used to apply the tr...

                                           issue_url  \
0  https://github.com/scikit-learn/scikit-learn/p...
1  https://github.com/scikit-learn/scikit-learn/p...
2  https://github.com/scikit-learn/scikit-learn/p...
3  https://github.com/scikit-learn/scikit-learn/p...
4  https://github.com/scikit-learn/scikit-learn/p...

                                      edit_functions problem_statement  \
0  sklearn/metrics/_plot/precision_recall_curve.p...
1  sklearn/feature_extraction/_hash.py:FeatureHas...
2  sklearn/decomposition/_kernel_pca.py:KernelPCA...
3
4

  comments                               pr_problem_statement pr_comments
0           ENH: Standardize parameter naming in Precision...
1           Set requires_fit=False for FeatureHasher and H...
2           Fix KernelPCA docstrings for transform functio...
3           CI Fix Azure install.sh bash regex match\nrhs ...
4           DOC Fix `pos_label` docstring in Display class...

In [13]:
qs = df["question"].values
filtered_df = results_df.loc[results_df["question"].isin(qs)]

In [14]:
filtered_df.describe()

,problem_statement,comments,pr_comments,precision_3,recall_3,f1_3,iou_3,precision_5,recall_5,f1_5,...,recall_10,f1_10,iou_10,mrr,bleu,meteor,bertscore,faithfulness,answer_relevancy,semantic_similarity
count,0.0,0.0,0.0,30.0,30.0,30.0,30.0,30.000000,30.000000,30.000000,...,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,0.0,0.0,30.000000
mean,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.020000,0.100000,0.033333,...,0.216667,0.043266,0.023864,0.038889,0.092589,0.354421,0.214500,NaN,NaN,0.697148
std,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.061026,0.305129,0.101710,...,0.408600,0.080149,0.044258,0.075694,0.074180,0.136969,0.126241,NaN,NaN,0.187266
min,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.007587,0.167364,-0.000752,NaN,NaN,0.159154
25%,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.051335,0.246270,0.129395,NaN,NaN,0.656068
50%,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.080044,0.320688,0.197761,NaN,NaN,0.749246
75%,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.112154,0.444130,0.296520,NaN,NaN,0.815643
max,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.200000,1.000000,0.333333,...,1.000000,0.222222,0.125000,0.250000,0.303471,0.634911,0.476287,NaN,NaN,0.905770