In [12]:
import pandas as pd

results_df = pd.read_csv("./data/eval_easy_w_metrics_codet5_simplererank.csv")
results_df

,function_code,category,question,answer,edit_functions,precision_3,recall_3,f1_3,iou_3,precision_5,...,bleu,meteor,bertscore,faithfulness,answer_relevancy,semantic_similarity,generated_answer,retrieved_functions,retrieved_docs,pred_query_class
0,-,general,What kinds of regression models and related me...,There are several regression models and relate...,"['IsotonicRegression.fit', 'IsotonicRegression...",0.000000,0.000000,0.000000,0.000000,0.000000,...,0.011941,0.085366,-0.025373,NaN,NaN,0.391317,"In scikit-learn, beginners can try the followi...","['BisectingKMeans.__sklearn_tags__', 'Quantile...","[Document(metadata={'type': 'function_name', '...",general_question
1,-,general,What PCA options are implemented?,Scikit-learn provides several dimensionality r...,"['IncrementalPCA.fit', 'IncrementalPCA.partial...",0.666667,0.181818,0.285714,0.166667,0.500000,...,0.013370,0.167464,0.005893,NaN,NaN,0.721299,"From the given context, it appears that the re...","['PCA._fit', 'PCA.fit', 'PCA.score', 'test_pca...","[Document(metadata={'type': 'function_name', '...",general_question
2,-,general,What decision tree models and related methods ...,There are several decision tree models and met...,"['MockDecisionTreeRegressor.predict', 'TestDec...",0.666667,0.153846,0.250000,0.142857,0.750000,...,0.018444,0.211397,0.231302,NaN,NaN,0.812335,The repository contains implementation of Deci...,"['BaseDecisionTree.decision_path', 'DecisionTr...","[Document(metadata={'type': 'function_name', '...",general_question
3,-,general,What kinds of data scaling methods are availab...,There are several data scaling methods impleme...,"['MinMaxScaler.fit', 'MinMaxScaler.partial_fit...",0.000000,0.000000,0.000000,0.000000,0.000000,...,0.033833,0.236009,0.175699,NaN,NaN,0.682233,The provided context primarily refers to clust...,"['BisectingKMeans.__sklearn_tags__', 'MultiTas...","[Document(metadata={'type': 'function_name', '...",general_question
4,-,general,What are the different data scaling or normali...,There are several normalizing and scaling meth...,"['MinMaxScaler.fit', 'MinMaxScaler.partial_fit...",0.000000,0.000000,0.000000,0.000000,0.000000,...,0.006691,0.136674,0.014618,NaN,NaN,0.685258,The repository implements three data scaling o...,"['MultiLabelBinarizer.fit_transform', 'Stackin...","[Document(metadata={'type': 'function_code', '...",general_question
5,-,general,What kinds of model evaluation metrics and sco...,There are many evaluation metrics and scoring ...,"['assert_best_scores_kept', 'accuracy_score', ...",0.000000,0.000000,0.000000,0.000000,0.000000,...,0.016442,0.093819,-0.019819,NaN,NaN,0.522285,The given context suggests that the repository...,"['DecisionTreeClassifier.predict_proba', 'Grad...","[Document(metadata={'type': 'function_name', '...",general_question
6,-,general,What kinds of forest-based models are implemen...,There are several forest-based models implemen...,"['BaseForest.apply', 'BaseForest.decision_path...",0.000000,0.000000,0.000000,0.000000,0.000000,...,0.018594,0.197686,0.076271,NaN,NaN,0.604884,"Based on the given context, it appears that th...","['homogeneity_completeness_v_measure', 'test_d...","[Document(metadata={'type': 'function_code', '...",general_question
7,-,general,Are there any encoder models implemented in th...,There are several encoding methods for categor...,"['ArffEncoder.encode', 'ArffEncoder.iter_encod...",0.000000,0.000000,0.000000,0.000000,0.000000,...,0.017840,0.252257,0.170930,NaN,NaN,0.515928,"Yes, based on the provided function and test n...","['test_one_hot_encoder_categories', 'test_one_...","[Document(metadata={'type': 'function_name', '...",general_question
8,-,general,What kinds of Gaussian-based models are implem...,There are several Gaussian-based models implem...,"['GaussianNB.fit', 'GaussianRandomProjection.t...",0.000000,0.000000,0.000000,0.000000,0.000000,...,0.030169,0.159273,0.170088,NaN,NaN,0.662701,"Based on the provided context, the repository ...","['CalibratedClassifierCV.fit', 'StackingRegres...","[Document(metadata={'type': 'function_code', '...",general_question
9,-,general,What kinds of covariance and related statistic...,There are several covariance and related stati...,"['EmpiricalCovariance.get_precision', 'Empiric...",0.666667,0.222222,0.333333,0.200000,0.400000,...,0.017376,0.299059,0.263137,NaN,NaN,0.725756,The repository appears to implement an Empiric...,"['EmpiricalCovariance._set_covariance', 'Empir...","[Document(metadata={'type': 'function_name', '...",general_question
10,-,general,Are there any outlier detection methods implem...,There are several outlier detection methods im...,"['OutlierMixin.fit_predict', 'LocalOutlierFact...",0.000000,0.000000,0.000000,0.000000,0.000000,...,0.048113,0.464646,0.189983,NaN,NaN,0.807979,"Based on the provided context, there appears t...",['BaseDistancesReductionDispatcher.is_usable_f...,"[Document(metadata={'type': 'function_name', '...",general_question
11,-,general,What kinds of component analysis (CA for short...,There are several component analysis methods i...,"['FastICA.fit', 'FastICA.transform', 'FastICA....",0.000000,0.000000,0.000000,0.000000,0.000000,...,0.008316,0.289352,0.040790,NaN,NaN,0.625447,The repository implements Linear Discriminant ...,['LinearDiscriminantAnalysis.__sklearn_tags__'...,"[Document(metadata={'type': 'function_name', '...",general_question
12,-,general,Can you show me the kernel functions implement...,There are several kernel functions implemented...,"['linear_kernel', 'polynomial_kernel', 'sigmoi...",0.000000,0.000000,0.000000,0.000000,0.000000,...,0.025736,0.265752,0.094278,NaN,NaN,0.583012,The repository implements a `KernelRidge.fit` ...,"['KernelRidge.fit', '_fit_context', 'parametri...","[Document(metadata={'type': 'function_name', '...",general_question
13,-,general,What options do I have for plotting evaluation...,There are several evaluation and diagnostic cu...,"['calibration_curve', 'det_curve', 'precision_...",0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012198,0.174419,0.123139,NaN,NaN,0.584381,"Based on the provided context, it appears that...","['CheckingClassifier.predict_proba', 'RFE.pred...","[Document(metadata={'type': 'function_code', '...",general_question
14,-,general,Any loss functions implemented in the repository?,There are several loss functions implemented i...,"['ridge_loss', 'log_dloss', 'zero_one_loss', '...",0.000000,0.000000,0.000000,0.000000,0.000000,...,0.145296,0.244349,0.182229,NaN,NaN,0.701345,"Yes, there appear to be multiple loss function...","['BaseLoss.loss', 'FeatureUnion.fit', 'LinearM...","[Document(metadata={'type': 'function_name', '...",general_question
15,-,general,How does `PCA.fit` work?,Fits a Principal Component Analysis (PCA) mode...,['PCA.fit'],0.000000,0.000000,0.000000,0.000000,0.200000,...,0.097722,0.402254,0.201084,NaN,NaN,0.702376,`PCA.fit` is a method in Principal Component A...,"['IncrementalPCA.fit', 'IncrementalPCA.partial...","[Document(metadata={'type': 'function_name', '...",general_question
16,-,general,How does `MaxAbsScaler.partial_fit` work?,"In simple terms, `MaxAbsScaler.partial_fit` is...",['MaxAbsScaler.partial_fit'],0.333333,1.000000,0.500000,0.333333,0.200000,...,0.046979,0.394175,0.312250,NaN,NaN,0.908053,The `MaxAbsScaler.partial_fit` function in the...,"['MaxAbsScaler.fit', 'MaxAbsScaler.inverse_tra...","[Document(metadata={'type': 'function_name', '...",general_question
17,-,general,How does `LocalOutlierFactor.score_samples` work?,The `LocalOutlierFactor.score_samples` functio...,['LocalOutlierFactor.score_samples'],0.000000,0.000000,0.000000,0.000000,0.250000,...,0.072067,0.279180,0.168098,NaN,NaN,0.745985,The `LocalOutlierFactor.score_samples` functio...,"['EllipticEnvelope.score_samples', 'LocalOutli...","[Document(metadata={'type': 'function_name', '...",general_question
18,-,general,How does `LogisticRegressionCV.fit` work?,"In a high level, `LogisticRegressionCV.fit` fu...",['LogisticRegressionCV.fit'],0.333333,1.000000,0.500000,0.333333,0.200000,...,0.142677,0.468750,0.406144,NaN,NaN,0.877120,`LogisticRegressionCV.fit` is a method used to...,"['LinearRegression.fit', 'LogisticRegression.f...","[Document(metadata={'type': 'function_name', '...",general_question
19,-,general,How does `silhouette_score` work?,The silhouette_score function computes the mea...,['silhouette_score'],0.333333,1.000000,0.500000,0.333333,0.333333,...,0.037253,0.366437,0.323480,NaN,NaN,0.937070,The `silhouette_score` function in the context...,"['silhouette_score', 'test_silhouette_reduce',...","[Document(metadata={'type': 'function_code', '...",general_question
20,-,general,How does `PCA.score_samples` work?,"In simple terms, `PCA.score_samples` calculate...",['PCA.score_samples'],0.000000,0.000000,0.000000,0.000000,0.250000,...,0.033782,0.285987,0.256188,NaN,NaN,0.593708,The `PCA.score_samples` function in Python's s...,"['EllipticEnvelope.score_samples', 'KernelDens...","[Document(metadata={'type': 'function_name', '...",general_question
21,-,general,How does `FastICA.fit` work?,"In a high level, `FastICA.fit` fits the Fast I...",['FastICA.fit'],0.333333,1.000000,0.500000,0.333333,0.250000,...,0.203621,0.509459,0.281399,NaN,NaN,0.915840,`FastICA.fit` is a method in the FastICA class...,"['FastICA._fit_transform', 'FastICA.fit', 'Fas...","[Document(metadata={'type': 'function_name', '...",general_question
22,-,general,How does `MaxAbsScaler.partial_fit` work?,"In simpler terms, `MaxAbsScaler.partial_fit` i...",['MaxAbsScaler.partial_fit'],0.333333,1.000000,0.500000,0.333333,0.200000,...,0.038280,0.270825,0.226390,NaN,NaN,0.687505,The `MaxAbsScaler.partial_fit` function in Sci...,"['MaxAbsScaler.fit', 'MaxAbsScaler.inverse_tra...","[Document(metadata={'type': 'function_name', '...",general_question
23,-,general,How does `LogisticRegression.predict_proba` work?,Calculates the probability of each class for a...,['LogisticRegression.predict_proba'],0.333333,1.000000,0.500000,0.333333,0.200000,...,0.035864,0.342586,0.273197,NaN,NaN,0.622902,`LogisticRegression.predict_proba` is a method...,['GradientBoostingClassifier.predict_log_proba...,"[Document(metadata={'type': 'function_name', '...",general_question
24,-,general,How does `hamming_loss` work?,The `hamming_loss` function calculates the ave...,['hamming_loss'],0.333333,1.000000,0.500000,0.333333,0.333333,...,0.093101,0.401499,0.301338,NaN,NaN,0.828070,The `hamming_loss` function calculates the fra...,"['hamming_loss', 'hinge_loss', 'test_multilabe...","[Document(metadata={'type': 'function_code', '...",general_question
25,-,general,How does `EmpiricalCovariance.score` work?,The `EmpiricalCovariance.score` function calcu...,['EmpiricalCovariance.score'],0.000000,0.000000,0.000000,0.000000,0.200000,...,0.040222,0.242718,0.279601,NaN,NaN,0.797411,`EmpiricalCovariance.score` is a function that...,"['EmpiricalCovariance.error_norm', 'EmpiricalC...","[Document(metadata={'type': 'function_name', '...",general_question
26,-,general,How does `PCA.fit` work?,"In a high level, PCA.fit function fits a Princ...",['PCA.fit'],0.000000,0.000000,0.000000,0.000000,0.200000,...,0.085162,0.356692,0.186132,NaN,NaN,0.827912,`PCA.fit` is a method used in Principal Compon...,"['IncrementalPCA.fit', 'IncrementalPCA.partial...","[Document(metadata={'type': 'function_name', '...",general_question
27,-,general,How does `KernelPCA.fit_transform` work?,Fits the Kernel PCA model to the input data X ...,['KernelPCA.fit_transform'],0.333333,1.000000,0.500000,0.333333,0.250000,...,0.063219,0.446825,0.153588,NaN,NaN,0.746253,`KernelPCA.fit_transform` is a method in the K...,"['KernelPCA._fit_inverse_transform', 'KernelPC...","[Document(metadata={'type': 'function_name', '...",general_question
28,-,general,How does `MockDecisionTreeRegressor.predict` w...,"Given input data X, this function predicts the...",['MockDecisionTreeRegressor.predict'],0.333333,1.000000,0.500000,0.333333,0.250000,...,0.031763,0.293218,0.168941,NaN,NaN,0.780711,The `MockDecisionTreeRegressor.predict` functi...,"['DecisionTreeRegressor.fit', 'GaussianProcess...","[Document(metadata={'type': 'function_name', '...",general_question
29,-,general,How does `laplacian_kernel` work?,The `laplacian_kernel` function computes the L...,['laplacian_kernel'],0.333333,1.000000,0.500000,0.333333,0.250000,...,0.058678,0.352680,0.219929,NaN,NaN,0.777289,"The `laplacian_kernel` function, based on the ...","['_laplacian_dense', '_laplacian_dense_flo', '...","[Document(metadata={'type': 'function_name', '...",general_question
30,-,general,How does `MockDecisionTreeRegressor.predict` w...,Predicts the output for the given input data X...,['MockDecisionTreeRegressor.predict'],0.333333,1.000000,0.500000,0.333333,0.250000,...,0.017792,0.203125,-0.015294,NaN,NaN,0.682921,The `MockDecisionTreeRegressor.predict` functi...,"['DecisionTreeRegressor.fit', 'GaussianProcess...","[Document(metadata={'type': 'function_name', '...",general_question
31,-,general,How does `LogisticRegressionCV.fit` work?,"In a high-level context, LogisticRegressionCV....",['LogisticRegressionCV.fit'],0.333333,1.000000,0.500000,0.333333,0.200000,...,0.018689,0.354986,0.311479,NaN,NaN,0.805501,`LogisticRegressionCV.fit` is a method used in...,"['LinearRegression.fit', 'LogisticRegression.f...","[Document(metadata={'type': 'function_name', '...",general_question
32,-,general,How does `BaseDecisionTree.decision_path` work?,"In simple terms, `BaseDecisionTree.decision_pa...",['BaseDecisionTree.decision_path'],0.333333,1.000000,0.500000,0.333333,0.250000,...,0.032648,0.307531,0.204143,NaN,NaN,0.681290,The function `BaseDecisionTree.decision_path` ...,"['BaseDecisionTree.decision_path', 'BaseDecisi...","[Document(metadata={'type': 'function_name', '...",general_question
33,-,general,How does `MinMaxScaler.inverse_transform` work?,Inverse_transform function takes in the scaled...,['MinMaxScaler.inverse_transform'],0.333333,1.000000,0.500000,0.333333,0.250000,...,0.023311,0.397216,0.263173,NaN,NaN,0.755774,The `MinMaxScaler.inverse_transform` function ...,"['MaxAbsScaler.inverse_transform', 'MinMaxScal...","[Document(metadata={'type': 'function_name', '...",general_question
34,-,general,How does `LogisticRegression.predict_proba` work?,"In a high level, `LogisticRegression.predict_p...",['LogisticRegression.predict_proba'],0.333333,1.000000,0.500000,0.333333,0.200000,...,0.040441,0.295349,0.296858,NaN,NaN,0.741808,The `LogisticRegression.predict_proba` functio...,['GradientBoostingClassifier.predict_log_proba...,"[Document(metadata={'type': 'function_name', '...",general_question
35,-,general,How does `MinMaxScaler.inverse_transform` work?,"Applies the inverse scaling to the input data,...",['MinMaxScaler.inverse_transform'],0.333333,1.000000,0.500000,0.333333,0.250000,...,0.031748,0.311804,0.196494,NaN,NaN,0.790386,`MinMaxScaler.inverse_transform` is a method i...,"['MaxAbsScaler.inverse_transform', 'MinMaxScal...","[Document(metadata={'type': 'function_name', '...",general_question
36,-,general,How does `PCA.fit` work?,The function `PCA.fit` takes in a dataset X (a...,['PCA.fit'],0.000000,0.000000,0.000000,0.000000,0.200000,...,0.048634,0.404777,0.275111,NaN,NaN,0.862814,`PCA.fit` is a method used to fit a PCA (Princ...,"['IncrementalPCA.fit', 'IncrementalPCA.partial...","[Document(metadata={'type': 'function_name', '...",general_question
37,-,general,How does `OneHotEncoder.get_feature_names_out`...,The `OneHotEncoder.get_feature_names_out` func...,['OneHotEncoder.get_feature_names_out'],0.333333,1.000000,0.500000,0.333333,0.200000,...,0.101939,0.246318,0.252191,NaN,NaN,0.866364,The `OneHotEncoder.get_feature_names_out` func...,"['AdditiveChi2Sampler.get_feature_names_out', ...","[Document(metadata={'type': 'function_name', '...",general_question
38,-,general,How does `TargetEncoder.fit` work?,"In simple terms, `TargetEncoder.fit` is a meth...",['TargetEncoder.fit'],0.333333,1.000000,0.500000,0.333333,0.250000,...,0.123254,0.496371,0.210696,NaN,NaN,0.882001,`TargetEncoder.fit` is a method in the TargetE...,"['OneHotEncoder.fit', 'TargetEncoder.fit', 'Ta...","[Document(metadata={'type': 'function_name', '...",general_question
39,-,general,How does `OutlierMixin.fit_predict` work?,Fits the model on the input data X and returns...,['OutlierMixin.fit_predict'],0.333333,1.000000,0.500000,0.333333,0.250000,...,0.016807,0.278686,0.047939,NaN,NaN,0.581553,`OutlierMixin.fit_predict` is a method in a cl...,"['BaseMixture.fit_predict', 'ClusterMixin.fit_...","[Document(metadata={'type': 'function_name', '...",general_question
40,-,general,How does `MaxAbsScaler.fit` work?,The MaxAbsScaler.fit function computes the max...,['MaxAbsScaler.fit'],0.333333,1.000000,0.500000,0.333333,0.250000,...,0.216447,0.533949,0.475525,NaN,NaN,0.874327,`MaxAbsScaler.fit` is a function in the `sklea...,"['MaxAbsScaler.fit', 'MaxAbsScaler.inverse_tra...","[Document(metadata={'type': 'function_name', '...",general_question
41,-,general,How does `BaseForest.apply` work?,"In simple terms, the `BaseForest.apply` functi...",['BaseForest.apply'],0.333333,1.000000,0.500000,0.333333,0.250000,...,0.028454,0.194508,-0.010841,NaN,NaN,0.700489,"From the provided context, it appears that `Ba...","['BaseForest._validate_X_predict', 'BaseForest...","[Document(metadata={'type': 'function_name', '...",general_question
42,-,general,How does `IsotonicRegression.get_feature_names...,The `IsotonicRegression.get_feature_names_out`...,['IsotonicRegression.get_feature_names_out'],0.333333,1.000000,0.500000,0.333333,0.250000,...,0.100557,0.297712,0.282003,NaN,NaN,0.894134,The `IsotonicRegression.get_feature_names_out`...,"['IsotonicRegression.get_feature_names_out', '...","[Document(metadata={'type': 'function_name', '...",general_question
43,-,general,How does `MaxAbsScaler.fit` work?,"In simple terms, MaxAbsScaler.fit computes the...",['MaxAbsScaler.fit'],0.333333,1.000000,0.500000,0.333333,0.250000,...,0.059529,0.401926,0.300509,NaN,NaN,0.864716,The `MaxAbsScaler.fit` function in the context...,"['MaxAbsScaler.fit', 'MaxAbsScaler.inverse_tra...","[Document(metadata={'type': 'function_name', '...",general_question
44,-,general,How does `IncrementalPCA.fit` work?,IncrementalPCA.fit function fits the model inc...,['IncrementalPCA.fit'],0.333333,1.000000,0.500000,0.333333,0.333333,...,0.017938,0.198915,0.116681,NaN,NaN,0.761179,The `IncrementalPCA.fit` function in the conte...,"['IncrementalPCA.fit', 'IncrementalPCA.partial...","[Document(metadata={'type': 'function_code', '...",general_question
45,-,general,How does `LocalOutlierFactor.fit` work?,"In simple terms, LocalOutlierFactor.fit functi...",['LocalOutlierFactor.fit'],0.333333,1.000000,0.500000,0.333333,0.250000,...,0.101495,0.461646,0.378238,NaN,NaN,0.913817,The `LocalOutlierFactor.fit` function in the c...,"['LocalOutlierFactor._predict', 'LocalOutlierF...","[Document(metadata={'type': 'function_name', '...",general_question
46,-,general,How does `FastICA.fit` work?,"In a beginner-friendly manner, `FastICA.fit` f...",['FastICA.fit'],0.333333,1.000000,0.500000,0.333333,0.250000,...,0.074223,0.297682,0.145815,NaN,NaN,0.854418,`FastICA.fit` is a method used for training th...,"['FastICA._fit_transform', 'FastICA.fit', 'Fas...","[Document(metadata={'type': 'function_name', '...",general_question
47,-,general,How does `IsolationForest.score_samples` work?,The `IsolationForest.score_samples` function c...,['IsolationForest.score_samples'],0.000000,0.000000,0.000000,0.000000,0.250000,...,0.080701,0.388019,0.288482,NaN,NaN,0.826272,`IsolationForest.score_samples` is a function ...,"['IsolationForest._compute_score_samples', 'Is...","[Document(metadata={'type': 'function_name', '...",general_question

In [4]:
general_qa_df = results_df[results_df["pred_query_class"] == "general_question"]
general_qa_df

,question,answer,issue_url,edit_functions,problem_statement,comments,pr_problem_statement,pr_comments,precision_3,recall_3,...,bleu,meteor,bertscore,faithfulness,answer_relevancy,semantic_similarity,generated_answer,retrieved_functions,retrieved_docs,pred_query_class
0,How do you handle the concept of inheritance i...,"In a multilevel model, you can handle the conc...",https://github.com/scikit-learn/scikit-learn/p...,"['PrecisionRecallDisplay.__init__', 'Precision...",NaN,NaN,ENH: Standardize parameter naming in Precision...,NaN,0.0,0.0,...,0.046150,0.201030,0.099288,NaN,NaN,0.657242,The provided context doesn't explicitly explai...,"['scale', 'test_inverse_binarize_multiclass', ...","[Document(metadata={'type': 'function_name', '...",general_question
1,What is the purpose of setting `requires_fit=F...,"This change sets the `""requires_fit""` tag to `...",https://github.com/scikit-learn/scikit-learn/p...,"['FeatureHasher._get_tags', 'TfidfVectorizer._...",NaN,NaN,Set requires_fit=False for FeatureHasher and H...,NaN,0.0,0.0,...,0.106501,0.367414,0.280702,NaN,NaN,0.771452,Setting `requires_fit=False` for `FeatureHashe...,"['HashingVectorizer.__sklearn_tags__', 'Requir...","[Document(metadata={'type': 'function_name', '...",general_question
2,Why did the author?,This PR exposes the `requires_fit=False` tag f...,https://github.com/scikit-learn/scikit-learn/p...,"['FeatureHasher._more_tags', 'HashingVectorize...",NaN,NaN,MAINT: Add requires_fit=False tag for FeatureH...,NaN,0.0,0.0,...,0.009249,0.085470,0.005752,NaN,NaN,0.252176,The author likely wrote functions named 'tupli...,"['_check', 'check', 'is_clusterer', 'tuplify']","[Document(metadata={'type': 'function_name', '...",general_question
6,What is the primary purpose of the DBSCAN algo...,The DBSCAN algorithm is a density-based cluste...,https://github.com/scikit-learn/scikit-learn/p...,"['DBSCAN.fit_predict', 'dbscan']",NaN,NaN,DOC Enhance DBSCAN docstrings with clearer par...,NaN,0.0,0.0,...,0.017713,0.289784,0.162582,NaN,NaN,0.845033,The primary purpose of the DBSCAN algorithm in...,"['BaseSGDRegressor.partial_fit', 'HDBSCAN._wei...","[Document(metadata={'type': 'function_name', '...",general_question
7,What is the primary function used in the sciki...,The fetch_california_housing function in sklea...,https://github.com/scikit-learn/scikit-learn/p...,"['fetch_california_housing', 'fetch_olivetti_f...",NaN,NaN,MNT Remove redundant mkdir calls\n`get_data_ho...,NaN,0.0,0.0,...,0.076871,0.524174,0.067415,NaN,NaN,0.759323,The primary function in the scikit-learn libra...,"['BernoulliRBM.__sklearn_tags__', 'BisectingKM...","[Document(metadata={'type': 'function_name', '...",general_question
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262,What is the purpose of the recent change in th...,The change adds information to the docstring f...,https://github.com/scikit-learn/scikit-learn/p...,['cross_validate'],NaN,NaN,DOC Add info when `scoring = None` in `cross_v...,NaN,0.0,0.0,...,0.092763,0.417647,0.303503,NaN,NaN,0.746258,The change in the `cross_validate` function's ...,['BaseHistGradientBoosting._check_early_stoppi...,"[Document(metadata={'type': 'function_code', '...",general_question
263,What changes did the MAINT PR make to the skle...,The PR added deprecation warnings for the `_va...,https://github.com/scikit-learn/scikit-learn/p...,"['BaseEstimator._check_feature_names', 'BaseEs...",NaN,NaN,MAINT add deprecation for transition to new de...,NaN,0.0,0.0,...,0.007816,0.144928,0.150538,NaN,NaN,0.408419,The MAINT PR made changes to the sklearn libra...,"['BernoulliRBM.__sklearn_tags__', 'test_ledoit...","[Document(metadata={'type': 'function_name', '...",general_question
264,What is the issue this pull request is suppose...,The.,https://github.com/scikit-learn/scikit-learn/p...,"['config_context', 'set_config', 'sag_solver']",NaN,NaN,Adds convergence warning suppression via globa...,NaN,0.0,0.0,...,0.008697,0.172414,-0.289696,NaN,NaN,-0.007781,The Pull Request (PR) seems to address issues ...,"['_available_if_estimator_has', '_should_be_sk...","[Document(metadata={'type': 'function_code', '...",general_question
265,What is the purpose of the `get_response_value...,It is used to select the positive class for bi...,https://github.com/scikit-learn/scikit-learn/p...,['test_partial_dependence_binary_model_grid_re...,NaN,NaN,FIX: Fix for binary classifier prediction shap...,NaN,0.0,0.0,...,0.005913,0.150000,0.102504,NaN,NaN,0.306094,The `get_response_values` function in the cont...,"['get_namespace', 'pairwise_distances', 'valid...","[Document(metadata={'type': 'function_code', '...",general_question
267,What was the purpose of the recent changes in ...,The purpose was to document the version added ...,https://github.com/scikit-learn/scikit-learn/p...,['get_tags'],NaN,NaN,DOC: Document version added\nIt's useful to kn...,NaN,0.0,0.0,...,0.014207,0.212418,0.127452,NaN,NaN,0.466792,"Based on the context provided, it appears that...","['Birch.__sklearn_tags__', 'SparseCoder.__skle...","[Document(metadata={'type': 'function_name', '...",general_question

In [5]:
general_qa_df.describe()

,problem_statement,comments,pr_comments,precision_3,recall_3,f1_3,iou_3,precision_5,recall_5,f1_5,...,recall_10,f1_10,iou_10,mrr,bleu,meteor,bertscore,faithfulness,answer_relevancy,semantic_similarity
count,0.0,0.0,0.0,185.0,185.0,185.0,185.0,185.0,185.0,185.0,...,185.0,185.0,185.0,185.0,185.000000,185.000000,185.000000,0.0,0.0,185.000000
mean,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.055273,0.292660,0.145581,NaN,NaN,0.565077
std,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.067049,0.130386,0.156267,NaN,NaN,0.220015
min,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.003837,0.048077,-0.350718,NaN,NaN,-0.102198
25%,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.013125,0.192308,0.047047,NaN,NaN,0.428493
50%,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.032807,0.274052,0.133099,NaN,NaN,0.573205
75%,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.074446,0.368643,0.236856,NaN,NaN,0.734817
max,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.404271,0.818379,0.563033,NaN,NaN,0.940013

In [17]:
results_df.loc[results_df["pred_query_class"] == "bug_report", ['question']].iloc[0].values[0]

'** What is the likely cause of the non-deterministic failure of the `test_unsorted_indices` function in `SVC` when trained on dense vs sparse data?'

In [16]:
results_df.loc[results_df["pred_query_class"] == "bug_report", ['edit_functions']].iloc[0].values[0]

"['_BaseScorer._routing_repr', '_PassthroughScorer.__repr__', '_PassthroughScorer._routing_repr', 'Base.split', 'Class_1.split', 'Consumer.fit', 'OddEstimator.fit', 'TestDefaults.fit', 'TestDefaults.predict', 'TestDefaults.score']"

In [12]:
from ast import literal_eval
results_df.loc[results_df["pred_query_class"] == "bug_report", ["retrieved_docs"]].iloc[0].values[0]

'[Document(metadata={\'type\': \'issue_body\', \'node_id\': 31722, \'doc_id\': \'b6eaef59-a28f-4b25-97df-e0812c2e2001\', \'_id\': \'83b6e50c-5189-406d-bce4-df373f913bc8\', \'_collection_name\': \'rag_collection_all-MiniLM-L6-v2_cosine\'}, page_content=\'[<code>test_unsorted_indices</code>](https://github.com/scikit-learn/scikit-learn/blob/cfd5f7833dfb3794e711e79e4a3373e599d5a1f0/sklearn/svm/tests/tes\'), Document(metadata={\'type\': \'issue_body\', \'node_id\': 31722, \'doc_id\': \'0c32126a-083c-41ae-9d00-2d3a4b029bd9\', \'_id\': \'3e55a525-7a99-4ec9-838d-ffeb127a9fe8\', \'_collection_name\': \'rag_collection_all-MiniLM-L6-v2_cosine\'}, page_content=\'function occasionally fails on CI when comparing the coefficients of `SVC(kernel="linear", probability=True, random_state=0)` trained on dense vs\'), Document(metadata={\'type\': \'issue_body\', \'node_id\': 1905, \'doc_id\': \'989d2f30-8623-4077-a88c-a2d446466570\', \'_id\': \'de4043be-8932-42ff-a041-ed4bdb1a2901\', \'_collection_name\': \'rag_collection_all-MiniLM-L6-v2_cosine\'}, page_content=\'I recently installed scikit tool and when testing it got error. Test of the sparse Linear SVC with iris data set failed with the following assertion\'), Document(metadata={\'type\': \'issue_body\', \'node_id\': 2737, \'doc_id\': \'5ebc212a-df5a-4de7-a417-7c2d910fa0e4\', \'_id\': \'f5290052-6e59-4e68-b1f2-b11718459dc1\', \'_collection_name\': \'rag_collection_all-MiniLM-L6-v2_cosine\'}, page_content=\'---\\n\\n```\\nFAIL: sklearn.svm.tests.test_sparse.test_timeout\'), Document(metadata={\'type\': \'issue_body\', \'node_id\': 19654, \'doc_id\': \'f01d858a-1944-4bc3-bd5e-f44f1fcbb1ce\', \'_id\': \'b80bad74-33fb-4be4-9adf-499348202a59\', \'_collection_name\': \'rag_collection_all-MiniLM-L6-v2_cosine\'}, page_content=\'### Describe the bug\\r\\n\\r\\n*SVC().fit(X, y, w)* sometimes fails with sparse *X* and *w* containing some zeros, raising:\\r\\n```python\'), Document(metadata={\'type\': \'issue_body\', \'node_id\': 19447, \'doc_id\': \'40b44928-b426-422d-b429-47e1828dcf97\', \'_id\': \'ff07f9e0-a86e-455e-be0e-59395019b983\', \'_collection_name\': \'rag_collection_all-MiniLM-L6-v2_cosine\'}, page_content=\'I suspect some form of memoization or extreme low sensitivity happening in the SVC `predict_proba(...)` implementation whereby once a SVC model is\'), Document(metadata={\'type\': \'issue_body\', \'node_id\': 918, \'doc_id\': \'4f5e35a8-dffc-43be-81c1-de4caec57467\', \'_id\': \'79a3bc06-d64f-4b18-8b81-d616dc3489d8\', \'_collection_name\': \'rag_collection_all-MiniLM-L6-v2_cosine\'}, page_content=\'When the feature matrix `X` passed to an `SVC` is sparse and the kernel is a callable, it never gets called. Instead, the SVM seems to just go ahead\'), Document(metadata={\'type\': \'issue_body\', \'node_id\': 31722, \'doc_id\': \'91c58af5-ae70-4672-8d82-63b3738876fa\', \'_id\': \'2d828373-6f07-40bd-b890-aa4d628d1e65\', \'_collection_name\': \'rag_collection_all-MiniLM-L6-v2_cosine\'}, page_content=\'# make sure dense and sparse SVM give the same result\\n    assert_allclose(coef_dense, coef_sorted.toarray(), **tols)\\n```\'), Document(metadata={\'type\': \'issue_body\', \'node_id\': 21410, \'doc_id\': \'b74f85f3-24a9-4b1f-a933-71c506526878\', \'_id\': \'aa08757a-6c45-42c8-9e9f-83814e5ee070\', \'_collection_name\': \'rag_collection_all-MiniLM-L6-v2_cosine\'}, page_content="I\'ve noticed a rather strange behavior when using **Scikit-Learn\'s SVC** implementation. Using the **built-in rbf kernel** with SVC is **slower** by"), Document(metadata={\'type\': \'issue_body\', \'node_id\': 5150, \'doc_id\': \'60c3f1fc-af5d-4de8-810a-c14c01d8ff0e\', \'_id\': \'4f29ce44-be18-4e65-987b-283d67c8be62\', \'_collection_name\': \'rag_collection_all-MiniLM-L6-v2_cosine\'}, page_content=\'This bug appears in current master, and for any dense svm class.\')]'

In [21]:
results_df["pred_query_class"].value_counts()

pred_query_class
general_qa           98
feature_request      35
performance_issue    29
bug_report           20
Name: count, dtype: int64

In [13]:
eval_cols = ['precision_3', 'recall_3', 'f1_3', 'iou_3', 'precision_5', 'recall_5',
       'f1_5', 'iou_5', 'precision_10', 'recall_10', 'f1_10', 'iou_10', 'mrr',
       'bleu', 'meteor', 'bertscore',
       'semantic_similarity']
results_df.groupby("pred_query_class")[eval_cols].mean(numeric_only=True)

,precision_3,recall_3,f1_3,iou_3,precision_5,recall_5,f1_5,iou_5,precision_10,recall_10,f1_10,iou_10,mrr,bleu,meteor,bertscore,semantic_similarity
pred_query_class,,,,,,,,,,,,,,,,,
general_question,0.222222,0.553289,0.288938,0.191171,0.2,0.700725,0.284833,0.176767,0.196528,0.700725,0.28146,0.174416,0.383681,0.054987,0.307528,0.197294,0.744044

In [15]:
results_df_new.groupby("pred_query_class")[eval_cols].mean(numeric_only=True)

,precision_3,recall_3,f1_3,iou_3,precision_5,recall_5,f1_5,iou_5,precision_10,recall_10,f1_10,iou_10,mrr,bleu,meteor,bertscore,semantic_similarity
pred_query_class,,,,,,,,,,,,,,,,,
general_question,0.256944,0.574256,0.327307,0.225794,0.253472,0.699256,0.347982,0.233826,0.252108,0.699819,0.344708,0.231393,0.408185,0.060177,0.283719,0.174501,0.724031

In [14]:
results_df_new = pd.read_csv("./data/eval_easy_w_metrics_codet5_popularity_rerank.csv")
results_df_new

,function_code,category,question,answer,edit_functions,precision_3,recall_3,f1_3,iou_3,precision_5,...,bleu,meteor,bertscore,faithfulness,answer_relevancy,semantic_similarity,generated_answer,retrieved_functions,retrieved_docs,pred_query_class
0,-,general,What kinds of regression models and related me...,There are several regression models and relate...,"['IsotonicRegression.fit', 'IsotonicRegression...",0.000000,0.000000,0.000000,0.000000,0.000000,...,0.039989,0.228849,0.216391,NaN,NaN,0.505291,scikit-learn offers several regression models ...,"['BisectingKMeans._predict_recursive', '_check...","[Document(metadata={'type': 'function_code', '...",general_question
1,-,general,What PCA options are implemented?,Scikit-learn provides several dimensionality r...,"['IncrementalPCA.fit', 'IncrementalPCA.partial...",0.666667,0.181818,0.285714,0.166667,0.500000,...,0.007848,0.169851,0.061863,NaN,NaN,0.642976,"From the provided context, it appears that the...","['PCA._fit', 'PCA.fit', 'PCA.fit_transform', '...","[Document(metadata={'type': 'function_name', '...",general_question
2,-,general,What decision tree models and related methods ...,There are several decision tree models and met...,"['MockDecisionTreeRegressor.predict', 'TestDec...",0.333333,0.076923,0.125000,0.066667,0.200000,...,0.009148,0.145820,0.263175,NaN,NaN,0.651569,"The repository provides Decision Tree models, ...","['BaseDecisionTree.decision_path', 'GradientBo...","[Document(metadata={'type': 'function_code', '...",general_question
3,-,general,What kinds of data scaling methods are availab...,There are several data scaling methods impleme...,"['MinMaxScaler.fit', 'MinMaxScaler.partial_fit...",0.000000,0.000000,0.000000,0.000000,0.000000,...,0.035429,0.217082,0.207369,NaN,NaN,0.765096,The scikit-learn library provides various data...,"['ClassifierMixin.__sklearn_tags__', 'ClusterM...","[Document(metadata={'type': 'function_name', '...",general_question
4,-,general,What are the different data scaling or normali...,There are several normalizing and scaling meth...,"['MinMaxScaler.fit', 'MinMaxScaler.partial_fit...",0.000000,0.000000,0.000000,0.000000,0.000000,...,0.013199,0.162413,0.041694,NaN,NaN,0.665713,The repository implements several data scaling...,"['indexable', 'inplace_column_scale', 'inplace...","[Document(metadata={'type': 'function_code', '...",general_question
5,-,general,What kinds of model evaluation metrics and sco...,There are many evaluation metrics and scoring ...,"['assert_best_scores_kept', 'accuracy_score', ...",0.000000,0.000000,0.000000,0.000000,0.000000,...,0.015112,0.122038,0.154306,NaN,NaN,0.728293,The repository implements evaluation metrics s...,"['GaussianProcessRegressor.predict', 'Gradient...","[Document(metadata={'type': 'function_code', '...",general_question
6,-,general,What kinds of forest-based models are implemen...,There are several forest-based models implemen...,"['BaseForest.apply', 'BaseForest.decision_path...",0.000000,0.000000,0.000000,0.000000,0.000000,...,0.017962,0.173310,0.045271,NaN,NaN,0.566434,The provided context suggests that the reposit...,"['BaseSGDClassifier._fit_multiclass', '_safe_i...","[Document(metadata={'type': 'function_code', '...",general_question
7,-,general,Are there any encoder models implemented in th...,There are several encoding methods for categor...,"['ArffEncoder.encode', 'ArffEncoder.iter_encod...",0.000000,0.000000,0.000000,0.000000,0.000000,...,0.033089,0.218391,0.030266,NaN,NaN,0.561349,"Based on the provided context, there seems to ...","['CheckingClassifier.score', 'OneHotEncoder._m...","[Document(metadata={'type': 'function_code', '...",general_question
8,-,general,What kinds of Gaussian-based models are implem...,There are several Gaussian-based models implem...,"['GaussianNB.fit', 'GaussianRandomProjection.t...",0.333333,0.083333,0.133333,0.071429,0.200000,...,0.029318,0.312851,0.168322,NaN,NaN,0.813699,The repository implements a GaussianRandomProj...,"['BaseSGDRegressor.partial_fit', 'GaussianRand...","[Document(metadata={'type': 'function_code', '...",general_question
9,-,general,What kinds of covariance and related statistic...,There are several covariance and related stati...,"['EmpiricalCovariance.get_precision', 'Empiric...",0.666667,0.222222,0.333333,0.200000,0.500000,...,0.034177,0.236036,0.201968,NaN,NaN,0.711734,The repository implements EmpiricalCovariance ...,"['EmpiricalCovariance._set_covariance', 'Empir...","[Document(metadata={'type': 'function_code', '...",general_question
10,-,general,Are there any outlier detection methods implem...,There are several outlier detection methods im...,"['OutlierMixin.fit_predict', 'LocalOutlierFact...",0.000000,0.000000,0.000000,0.000000,0.000000,...,0.023509,0.286261,0.127063,NaN,NaN,0.743698,"Based on the provided context, there is no exp...","['_fit_context', 'get_namespace', 'is_outlier_...","[Document(metadata={'type': 'function_code', '...",general_question
11,-,general,What kinds of component analysis (CA for short...,There are several component analysis methods i...,"['FastICA.fit', 'FastICA.transform', 'FastICA....",0.000000,0.000000,0.000000,0.000000,0.000000,...,0.016443,0.381803,0.124561,NaN,NaN,0.615937,"From the context provided, it appears that the...","['_check_response_method', '_class_cov', '_pro...","[Document(metadata={'type': 'function_code', '...",general_question
12,-,general,Can you show me the kernel functions implement...,There are several kernel functions implemented...,"['linear_kernel', 'polynomial_kernel', 'sigmoi...",0.000000,0.000000,0.000000,0.000000,0.000000,...,0.012424,0.196784,0.033796,NaN,NaN,0.685576,The repository does not explicitly show kernel...,"['QuantileRegressor.__sklearn_tags__', '_check...","[Document(metadata={'type': 'function_code', '...",general_question
13,-,general,What options do I have for plotting evaluation...,There are several evaluation and diagnostic cu...,"['calibration_curve', 'det_curve', 'precision_...",0.000000,0.000000,0.000000,0.000000,0.000000,...,0.011727,0.171429,-0.009192,NaN,NaN,0.546688,"Based on the given context, it seems that the ...",['GradientBoostingClassifier.decision_function...,"[Document(metadata={'type': 'function_code', '...",general_question
14,-,general,Any loss functions implemented in the repository?,There are several loss functions implemented i...,"['ridge_loss', 'log_dloss', 'zero_one_loss', '...",0.000000,0.000000,0.000000,0.000000,0.000000,...,0.180028,0.175953,0.222652,NaN,NaN,0.675380,"Yes, there are loss functions implemented in t...","['BaseLoss.loss', 'LinearModelLoss.loss', 'Lin...","[Document(metadata={'type': 'function_code', '...",general_question
15,-,general,How does `PCA.fit` work?,Fits a Principal Component Analysis (PCA) mode...,['PCA.fit'],0.333333,1.000000,0.500000,0.333333,0.333333,...,0.154512,0.508780,0.310055,NaN,NaN,0.731149,`PCA.fit` is a method in the Principal Compone...,"['PCA._fit', 'PCA.fit', 'PCA.fit_transform']","[Document(metadata={'type': 'function_name', '...",general_question
16,-,general,How does `MaxAbsScaler.partial_fit` work?,"In simple terms, `MaxAbsScaler.partial_fit` is...",['MaxAbsScaler.partial_fit'],0.333333,1.000000,0.500000,0.333333,0.200000,...,0.052476,0.389377,0.348248,NaN,NaN,0.697809,The `MaxAbsScaler.partial_fit` function in the...,"['MaxAbsScaler.fit', 'MaxAbsScaler.partial_fit...","[Document(metadata={'type': 'function_name', '...",general_question
17,-,general,How does `LocalOutlierFactor.score_samples` work?,The `LocalOutlierFactor.score_samples` functio...,['LocalOutlierFactor.score_samples'],0.333333,1.000000,0.500000,0.333333,0.333333,...,0.064260,0.252265,0.231998,NaN,NaN,0.722590,The `LocalOutlierFactor.score_samples` functio...,"['LocalOutlierFactor._predict', 'LocalOutlierF...","[Document(metadata={'type': 'function_name', '...",general_question
18,-,general,How does `LogisticRegressionCV.fit` work?,"In a high level, `LogisticRegressionCV.fit` fu...",['LogisticRegressionCV.fit'],0.333333,1.000000,0.500000,0.333333,0.333333,...,0.107712,0.368220,0.246888,NaN,NaN,0.828355,The function `LogisticRegressionCV.fit` is not...,"['LogisticRegression.fit', 'LogisticRegression...","[Document(metadata={'type': 'function_code', '...",general_question
19,-,general,How does `silhouette_score` work?,The silhouette_score function computes the mea...,['silhouette_score'],0.333333,1.000000,0.500000,0.333333,0.333333,...,0.119751,0.432882,0.429189,NaN,NaN,0.898060,The `silhouette_score` is a method in scikit-l...,"['check_is_fitted', 'silhouette_score', 'test_...","[Document(metadata={'type': 'function_code', '...",general_question
20,-,general,How does `PCA.score_samples` work?,"In simple terms, `PCA.score_samples` calculate...",['PCA.score_samples'],0.333333,1.000000,0.500000,0.333333,0.200000,...,0.036770,0.298172,0.274508,NaN,NaN,0.776580,The `PCA.score_samples` function in the given ...,"['CheckingClassifier._check_X_y', 'PCA.score',...","[Document(metadata={'type': 'function_name', '...",general_question
21,-,general,How does `FastICA.fit` work?,"In a high level, `FastICA.fit` fits the Fast I...",['FastICA.fit'],0.500000,1.000000,0.666667,0.500000,0.500000,...,0.139558,0.412851,0.275925,NaN,NaN,0.858023,`FastICA.fit` is a function in the FastICA lib...,"['FastICA._fit_transform', 'FastICA.fit']","[Document(metadata={'type': 'function_name', '...",general_question
22,-,general,How does `MaxAbsScaler.partial_fit` work?,"In simpler terms, `MaxAbsScaler.partial_fit` i...",['MaxAbsScaler.partial_fit'],0.333333,1.000000,0.500000,0.333333,0.200000,...,0.136495,0.309491,0.242544,NaN,NaN,0.809253,`MaxAbsScaler.partial_fit` is an incremental f...,"['MaxAbsScaler.fit', 'MaxAbsScaler.partial_fit...","[Document(metadata={'type': 'function_name', '...",general_question
23,-,general,How does `LogisticRegression.predict_proba` work?,Calculates the probability of each class for a...,['LogisticRegression.predict_proba'],0.000000,0.000000,0.000000,0.000000,0.200000,...,0.087357,0.291160,0.157291,NaN,NaN,0.584427,The `LogisticRegression.predict_proba` functio...,"['BaggingClassifier.predict_proba', 'BaseSearc...","[Document(metadata={'type': 'function_name', '...",general_question
24,-,general,How does `hamming_loss` work?,The `hamming_loss` function calculates the ave...,['hamming_loss'],0.333333,1.000000,0.500000,0.333333,0.250000,...,0.034073,0.251938,0.182870,NaN,NaN,0.662825,The `hamming_loss` is a function in the given ...,"['_check_params_groups_deprecation', 'hamming_...","[Document(metadata={'type': 'function_code', '...",general_question
25,-,general,How does `EmpiricalCovariance.score` work?,The `EmpiricalCovariance.score` function calcu...,['EmpiricalCovariance.score'],0.333333,1.000000,0.500000,0.333333,0.333333,...,0.067543,0.225564,0.043702,NaN,NaN,0.682901,The `EmpiricalCovariance.score` function in th...,"['EmpiricalCovariance.fit', 'EmpiricalCovarian...","[Document(metadata={'type': 'function_name', '...",general_question
26,-,general,How does `PCA.fit` work?,"In a high level, PCA.fit function fits a Princ...",['PCA.fit'],0.333333,1.000000,0.500000,0.333333,0.333333,...,0.086552,0.305129,0.176315,NaN,NaN,0.784188,`PCA.fit` is a function in the Principal Compo...,"['PCA._fit', 'PCA.fit', 'PCA.fit_transform']","[Document(metadata={'type': 'function_name', '...",general_question
27,-,general,How does `KernelPCA.fit_transform` work?,Fits the Kernel PCA model to the input data X ...,['KernelPCA.fit_transform'],0.000000,0.000000,0.000000,0.000000,0.250000,...,0.078223,0.429236,0.166931,NaN,NaN,0.788850,`KernelPCA.fit_transform` is a method that fit...,"['KernelPCA._fit_inverse_transform', 'KernelPC...","[Document(metadata={'type': 'function_name', '...",general_question
28,-,general,How does `MockDecisionTreeRegressor.predict` w...,"Given input data X, this function predicts the...",['MockDecisionTreeRegressor.predict'],0.500000,1.000000,0.666667,0.500000,0.500000,...,0.018966,0.164093,0.058874,NaN,NaN,0.610405,The `MockDecisionTreeRegressor.predict` functi...,"['AdaBoostRegressor.predict', 'MockDecisionTre...","[Document(metadata={'type': 'function_name', '...",general_question
29,-,general,How does `laplacian_kernel` work?,The `laplacian_kernel` function computes the L...,['laplacian_kernel'],0.000000,0.000000,0.000000,0.000000,0.200000,...,0.102660,0.455046,0.321118,NaN,NaN,0.806690,The `laplacian_kernel` function in the given c...,"['_kmeans_plusplus', 'barycenter_kneighbors_gr...","[Document(metadata={'type': 'function_name', '...",general_question
30,-,general,How does `MockDecisionTreeRegressor.predict` w...,Predicts the output for the given input data X...,['MockDecisionTreeRegressor.predict'],0.500000,1.000000,0.666667,0.500000,0.500000,...,0.029294,0.252772,-0.019116,NaN,NaN,0.612674,The `MockDecisionTreeRegressor.predict` functi...,"['AdaBoostRegressor.predict', 'MockDecisionTre...","[Document(metadata={'type': 'function_name', '...",general_question
31,-,general,How does `LogisticRegressionCV.fit` work?,"In a high-level context, LogisticRegressionCV....",['LogisticRegressionCV.fit'],0.333333,1.000000,0.500000,0.333333,0.333333,...,0.064703,0.304706,0.183052,NaN,NaN,0.774881,The function `LogisticRegressionCV.fit` is not...,"['LogisticRegression.fit', 'LogisticRegression...","[Document(metadata={'type': 'function_code', '...",general_question
32,-,general,How does `BaseDecisionTree.decision_path` work?,"In simple terms, `BaseDecisionTree.decision_pa...",['BaseDecisionTree.decision_path'],0.333333,1.000000,0.500000,0.333333,0.333333,...,0.028021,0.243934,0.002444,NaN,NaN,0.602458,`BaseDecisionTree.decision_path` in this conte...,"['BaseDecisionTree.apply', 'BaseDecisionTree.c...","[Document(metadata={'type': 'function_name', '...",general_question
33,-,general,How does `MinMaxScaler.inverse_transform` work?,Inverse_transform function takes in the scaled...,['MinMaxScaler.inverse_transform'],0.333333,1.000000,0.500000,0.333333,0.250000,...,0.022473,0.251678,0.158749,NaN,NaN,0.745370,`MinMaxScaler.inverse_transform` is a method i...,"['MinMaxScaler.inverse_transform', 'MinMaxScal...","[Document(metadata={'type': 'function_name', '...",general_question
34,-,general,How does `LogisticRegression.predict_proba` work?,"In a high level, `LogisticRegression.predict_p...",['LogisticRegression.predict_proba'],0.000000,0.000000,0.000000,0.000000,0.200000,...,0.032361,0.207424,0.218342,NaN,NaN,0.768104,The `LogisticRegression.predict_proba` method ...,"['BaggingClassifier.predict_proba', 'BaseSearc...","[Document(metadata={'type': 'function_name', '...",general_question
35,-,general,How does `MinMaxScaler.inverse_transform` work?,"Applies the inverse scaling to the input data,...",['MinMaxScaler.inverse_transform'],0.333333,1.000000,0.500000,0.333333,0.250000,...,0.037126,0.286041,0.192847,NaN,NaN,0.849090,The `MinMaxScaler.inverse_transform` function ...,"['MinMaxScaler.inverse_transform', 'MinMaxScal...","[Document(metadata={'type': 'function_name', '...",general_question
36,-,general,How does `PCA.fit` work?,The function `PCA.fit` takes in a dataset X (a...,['PCA.fit'],0.333333,1.000000,0.500000,0.333333,0.333333,...,0.130738,0.365018,0.296020,NaN,NaN,0.860003,`PCA.fit` is a function in Principal Component...,"['PCA._fit', 'PCA.fit', 'PCA.fit_transform']","[Document(metadata={'type': 'function_name', '...",general_question
37,-,general,How does `OneHotEncoder.get_feature_names_out`...,The `OneHotEncoder.get_feature_names_out` func...,['OneHotEncoder.get_feature_names_out'],0.333333,1.000000,0.500000,0.333333,0.250000,...,0.085735,0.342294,0.248578,NaN,NaN,0.852179,The `OneHotEncoder.get_feature_names_out` func...,['OneHotEncoder._check_get_feature_name_combin...,"[Document(metadata={'type': 'function_code', '...",general_question
38,-,general,How does `TargetEncoder.fit` work?,"In simple terms, `TargetEncoder.fit` is a meth...",['TargetEncoder.fit'],0.333333,1.000000,0.500000,0.333333,0.333333,...,0.137944,0.407841,0.241571,NaN,NaN,0.807109,`TargetEncoder.fit` is a method in the TargetE...,"['TargetEncoder._fit_encoding_multiclass', 'Ta...","[Document(metadata={'type': 'function_name', '...",general_question
39,-,general,How does `OutlierMixin.fit_predict` work?,Fits the model on the input data X and returns...,['OutlierMixin.fit_predict'],0.000000,0.000000,0.000000,0.000000,0.200000,...,0.011667,0.148026,0.047181,NaN,NaN,0.558473,`OutlierMixin.fit_predict` is a method that tr...,"['BaseMixture.fit_predict', 'ClusterMixin.fit_...","[Document(metadata={'type': 'function_name', '...",general_question
40,-,general,How does `MaxAbsScaler.fit` work?,The MaxAbsScaler.fit function computes the max...,['MaxAbsScaler.fit'],0.500000,1.000000,0.666667,0.500000,0.500000,...,0.024292,0.281632,0.178912,NaN,NaN,0.857840,The `MaxAbsScaler.fit` function in the context...,"['MaxAbsScaler.fit', 'MaxAbsScaler.partial_fit']","[Document(metadata={'type': 'function_name', '...",general_question
41,-,general,How does `BaseForest.apply` work?,"In simple terms, the `BaseForest.apply` functi...",['BaseForest.apply'],0.500000,1.000000,0.666667,0.500000,0.500000,...,0.077728,0.238065,0.018744,NaN,NaN,0.501944,"In the given context, the `BaseForest.apply` f...","['BaseForest.apply', 'BaseGradientBoosting.app...","[Document(metadata={'type': 'function_name', '...",general_question
42,-,general,How does `IsotonicRegression.get_feature_names...,The `IsotonicRegression.get_feature_names_out`...,['IsotonicRegression.get_feature_names_out'],0.333333,1.000000,0.500000,0.333333,0.200000,...,0.109063,0.531615,0.331680,NaN,NaN,0.856162,The `IsotonicRegression.get_feature_names_out`...,"['IsotonicRegression._build_y', 'IsotonicRegre...","[Document(metadata={'type': 'function_name', '...",general_question
43,-,general,How does `MaxAbsScaler.fit` work?,"In simple terms, MaxAbsScaler.fit computes the...",['MaxAbsScaler.fit'],0.500000,1.000000,0.666667,0.500000,0.500000,...,0.097026,0.456093,0.286883,NaN,NaN,0.864941,`MaxAbsScaler.fit` is a method in the `sklearn...,"['MaxAbsScaler.fit', 'MaxAbsScaler.partial_fit']","[Document(metadata={'type': 'function_name', '...",general_question
44,-,general,How does `IncrementalPCA.fit` work?,IncrementalPCA.fit function fits the model inc...,['IncrementalPCA.fit'],0.500000,1.000000,0.666667,0.500000,0.500000,...,0.029549,0.189531,0.164268,NaN,NaN,0.762915,The `IncrementalPCA.fit` function in the given...,"['IncrementalPCA.fit', 'IncrementalPCA.partial...","[Document(metadata={'type': 'function_code', '...",general_question
45,-,general,How does `LocalOutlierFactor.fit` work?,"In simple terms, LocalOutlierFactor.fit functi...",['LocalOutlierFactor.fit'],0.333333,1.000000,0.500000,0.333333,0.333333,...,0.033973,0.237578,0.192037,NaN,NaN,0.781115,The `LocalOutlierFactor.fit` method is a funct...,"['LocalOutlierFactor._predict', 'LocalOutlierF...","[Document(metadata={'type': 'function_name', '...",general_question
46,-,general,How does `FastICA.fit` work?,"In a beginner-friendly manner, `FastICA.fit` f...",['FastICA.fit'],0.500000,1.000000,0.666667,0.500000,0.500000,...,0.092271,0.321867,0.112043,NaN,NaN,0.737570,`FastICA.fit` is a method in the FastICA packa...,"['FastICA._fit_transform', 'FastICA.fit']","[Document(metadata={'type': 'function_name', '...",general_question
47,-,general,How does `IsolationForest.score_samples` work?,The `IsolationForest.score_samples` function c...,['IsolationForest.score_samples'],0.000000,0.000000,0.000000,0.000000,0.250000,...,0.078220,0.259331,0.165860,NaN,NaN,0.839127,"The `IsolationForest.score_samples` function, ...",['IsolationForest._compute_chunked_score_sampl...,"[Document(metadata={'type': 'function_name', '...",general_question

In [7]:
import csv 

rows = []
with open('./data/eval_prs_filtered.csv',newline='') as csvfile:
    spamreader = csv.reader(csvfile,delimiter=';')
    for row in spamreader:
        rows.append(row)

df = pd.DataFrame(rows[1:], columns=rows[0])
print(df.head())

                                            question  \
0  How do you handle the concept of inheritance i...
1  What is the purpose of setting `requires_fit=F...
2  What is the purpose of the `transform` functio...
3  Why was the CI check modified in the Azure ins...
4  What is the purpose of the `transform` method ...

                                              answer  \
0  In a multilevel model, you can handle the conc...
1  This change sets the `"requires_fit"` tag to `...
2  It applies the learned linear transformation t...
3  The CI check was modified to remove quotes fro...
4  The `transform` method is used to apply the tr...

                                           issue_url  \
0  https://github.com/scikit-learn/scikit-learn/p...
1  https://github.com/scikit-learn/scikit-learn/p...
2  https://github.com/scikit-learn/scikit-learn/p...
3  https://github.com/scikit-learn/scikit-learn/p...
4  https://github.com/scikit-learn/scikit-learn/p...

                                      edit_functions problem_statement  \
0  sklearn/metrics/_plot/precision_recall_curve.p...
1  sklearn/feature_extraction/_hash.py:FeatureHas...
2  sklearn/decomposition/_kernel_pca.py:KernelPCA...
3
4

  comments                               pr_problem_statement pr_comments
0           ENH: Standardize parameter naming in Precision...
1           Set requires_fit=False for FeatureHasher and H...
2           Fix KernelPCA docstrings for transform functio...
3           CI Fix Azure install.sh bash regex match\nrhs ...
4           DOC Fix `pos_label` docstring in Display class...

In [8]:
qs = df["question"].values
filtered_df = results_df.loc[results_df["question"].isin(qs)]

In [9]:
filtered_df.describe()

,problem_statement,comments,pr_comments,precision_3,recall_3,f1_3,iou_3,precision_5,recall_5,f1_5,...,recall_10,f1_10,iou_10,mrr,bleu,meteor,bertscore,faithfulness,answer_relevancy,semantic_similarity
count,0.0,0.0,0.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,...,30.0,30.0,30.0,30.0,30.000000,30.000000,30.000000,0.0,0.0,30.000000
mean,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.100275,0.362080,0.224866,NaN,NaN,0.717895
std,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.093264,0.110230,0.165937,NaN,NaN,0.173241
min,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.010854,0.193370,-0.045306,NaN,NaN,0.215636
25%,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.048515,0.284917,0.101957,NaN,NaN,0.636401
50%,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.074896,0.361031,0.195434,NaN,NaN,0.763693
75%,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.117129,0.432616,0.352806,NaN,NaN,0.844300
max,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.404271,0.600093,0.563033,NaN,NaN,0.931943

In [11]:
filtered_df["pred_query_class"].value_counts()

pred_query_class
general_question     22
performance_issue     4
feature_request       3
bug_report            1
Name: count, dtype: int64

In [10]:
filtered_df.groupby("pred_query_class")[eval_cols].mean(numeric_only=True)

,precision_3,recall_3,f1_3,iou_3,precision_5,recall_5,f1_5,iou_5,precision_10,recall_10,f1_10,iou_10,mrr,bleu,meteor,bertscore,semantic_similarity
pred_query_class,,,,,,,,,,,,,,,,,
bug_report,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.110989,0.355290,0.178603,0.740046
feature_request,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.050763,0.326828,0.153991,0.531229
general_question,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.108676,0.366702,0.246230,0.735753
performance_issue,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.088526,0.364798,0.172088,0.754141